// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckEnvironmentKey():Promise<boolean>;

export function ConnectWithApiKey(arg1:string):Promise<void>;

export function DeleteBlob(arg1:string):Promise<void>;

export function DeleteCache(arg1:string):Promise<void>;

export function DeleteValue(arg1:string):Promise<void>;

export function DownloadBlob(arg1:string):Promise<string>;

export function GetActiveSubscriptions():Promise<Array<string>>;

export function GetBlobInfo(arg1:string):Promise<string>;

export function GetCache(arg1:string):Promise<string>;

export function GetRequiresApiKey():Promise<boolean>;

export function GetValue(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function PublishEvent(arg1:string,arg2:string):Promise<void>;

export function PurgeAllSubscribers():Promise<number>;

export function SearchBlobs(arg1:string,arg2:number,arg3:number):Promise<main.KeyListResult>;

export function SearchCache(arg1:string,arg2:number,arg3:number):Promise<main.KeyListResult>;

export function SearchValues(arg1:string,arg2:number,arg3:number):Promise<main.KeyListResult>;

export function SetCache(arg1:string,arg2:string):Promise<void>;

export function SetValue(arg1:string,arg2:string):Promise<void>;

export function SubscribeToTopic(arg1:string):Promise<void>;

export function UnsubscribeFromAll():Promise<void>;

export function UnsubscribeFromTopic(arg1:string):Promise<void>;

export function UploadBlob(arg1:string):Promise<void>;
