// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteBlob(arg1) {
  return window['go']['main']['App']['DeleteBlob'](arg1);
}

export function DeleteCache(arg1) {
  return window['go']['main']['App']['DeleteCache'](arg1);
}

export function DeleteValue(arg1) {
  return window['go']['main']['App']['DeleteValue'](arg1);
}

export function DownloadBlob(arg1) {
  return window['go']['main']['App']['DownloadBlob'](arg1);
}

export function GetActiveSubscriptions() {
  return window['go']['main']['App']['GetActiveSubscriptions']();
}

export function GetBlobInfo(arg1) {
  return window['go']['main']['App']['GetBlobInfo'](arg1);
}

export function GetCache(arg1) {
  return window['go']['main']['App']['GetCache'](arg1);
}

export function GetRequiresApiKey() {
  return window['go']['main']['App']['GetRequiresApiKey']();
}

export function GetValue(arg1) {
  return window['go']['main']['App']['GetValue'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PublishEvent(arg1, arg2) {
  return window['go']['main']['App']['PublishEvent'](arg1, arg2);
}

export function PurgeAllSubscribers() {
  return window['go']['main']['App']['PurgeAllSubscribers']();
}

export function SearchBlobs(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchBlobs'](arg1, arg2, arg3);
}

export function SearchCache(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchCache'](arg1, arg2, arg3);
}

export function SearchValues(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchValues'](arg1, arg2, arg3);
}

export function SetCache(arg1, arg2) {
  return window['go']['main']['App']['SetCache'](arg1, arg2);
}

export function SetValue(arg1, arg2) {
  return window['go']['main']['App']['SetValue'](arg1, arg2);
}

export function SubscribeToTopic(arg1) {
  return window['go']['main']['App']['SubscribeToTopic'](arg1);
}

export function UnsubscribeFromAll() {
  return window['go']['main']['App']['UnsubscribeFromAll']();
}

export function UnsubscribeFromTopic(arg1) {
  return window['go']['main']['App']['UnsubscribeFromTopic'](arg1);
}

export function UploadBlob(arg1) {
  return window['go']['main']['App']['UploadBlob'](arg1);
}
