name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        build:
          - name: loxhaus-windows-amd64.exe
            platform: windows
            arch: amd64
            os: windows-latest
          - name: loxhaus-windows-arm64.exe
            platform: windows
            arch: arm64
            os: windows-latest
          - name: loxhaus-linux-amd64
            platform: linux
            arch: amd64
            os: ubuntu-latest
          - name: loxhaus-linux-arm64
            platform: linux
            arch: arm64
            os: ubuntu-latest
          - name: loxhaus-darwin-amd64
            platform: darwin
            arch: amd64
            os: macos-latest
          - name: loxhaus-darwin-arm64
            platform: darwin
            arch: arm64
            os: macos-latest
          - name: loxhaus-darwin-universal
            platform: darwin
            arch: universal
            os: macos-latest

    runs-on: ${{ matrix.build.os }}
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev

    - name: Build
      run: |
        wails build -platform ${{ matrix.build.platform }}/${{ matrix.build.arch }} -o build/bin/${{ matrix.build.name }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.build.name }}
        path: build/bin/${{ matrix.build.name }}
